services:
  # Web Service for the main application
  - type: web
    name: brillprime-app
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: brill-prime-mobile
          property: connectionString
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_APPLE_CLIENT_ID
        sync: false
      - key: VITE_FACEBOOK_APP_ID
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health
    disk:
      name: brillprime-disk
      mountPath: /opt/render/project/uploads
      sizeGB: 1

  # Admin Dashboard (if needed separately)
  - type: web
    name: brillprime-admin
    runtime: node
    plan: starter
    buildCommand: cd admin-dashboard && npm install && npm run build
    startCommand: cd admin-dashboard && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: brill-prime-mobile
          property: connectionString
      - key: VITE_API_BASE_URL
        value: https://brillprime-app.onrender.com
    healthCheckPath: /

databases:
  # PostgreSQL Database - Using your existing database
  - name: brill-prime-mobile
    databaseName: brillprimedb
    user: brill_prime
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"