
services:
  - type: web
    name: brillprime-backend
    env: node
    plan: free
    buildCommand: |
      npm install --legacy-peer-deps
    startCommand: NODE_ENV=production npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        value: postgresql://brillprimemobiledb_user:ymhSFdyAdL7cRbCzJwUgjXwEufSsTh89@dpg-d2npgb6r433s73ah5qqg-a.oregon-postgres.render.com:5432/brillprimemobiledb
      - key: REDIS_DISABLED
        value: true
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-repl.replit.app
      - key: CLIENT_URL
        value: https://your-frontend-repl.replit.app
      - key: BASE_URL
        value: https://your-backend-repl.replit.app
      - key: WEBSOCKET_URL
        value: wss://your-backend-repl.replit.app
      - key: CORS_ORIGIN
        value: https://your-frontend-repl.replit.app
      - key: TRUSTED_PROXIES
        value: replit
