services:
  - type: web
    name: brillprime-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: brillprimedb
          property: connectionString
    healthCheckPath: /health
    
databases:
  - name: brillprimedb
    databaseName: brillprimedb
    user: brill_prime
    plan: free